<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MUMTEWD0500" name="Command line test 7d8dff44-ba9f-44a5-bf9d-ada7afe1e159" tests="3" failures="1" timestamp="9 Aug 2018 10:17:03 GMT" time="14.77" errors="0">
  <testcase name="tiLogin" time="2.75" classname="com.TIautomation.TimesInfluence.TIlogin"/>
  <testcase name="tiLogin" time="2.688" classname="com.TIautomation.TimesInfluence.TIlogin"/>
  <testcase name="tiLogin" time="2.4" classname="com.TIautomation.TimesInfluence.TIlogin">
    <failure type="java.lang.AssertionError" message="Test case passed expected [logged in] but found [http://uat.timesinfluence.com/#/pitch]">
      <![CDATA[java.lang.AssertionError: Test case passed expected [logged in] but found [http://uat.timesinfluence.com/#/pitch]
	at com.TIautomation.TimesInfluence.TIlogin.tiLogin(TIlogin.java:79)
	at com.mentorstudies.automationframework.TestRunner.main(TestRunner.java:117)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
	at java.lang.Thread.run(Thread.java:748)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- tiLogin -->
</testsuite> <!-- Command line test 7d8dff44-ba9f-44a5-bf9d-ada7afe1e159 -->
